/*
 * Iris is a World Generator for Minecraft Servers
 * Copyright (c) 2026 Arcane Arts (Volmit Software)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package art.arcane.iris.modded.command;

import art.arcane.iris.modded.ModdedIrisLog;
import art.arcane.iris.generation.runtime.Engine;
import art.arcane.iris.structure.placement.IrisStructureLocator;
import art.arcane.iris.structure.nativegen.NativeStructureGenerationPolicy;
import art.arcane.iris.structure.placement.StructureReachability;
import art.arcane.iris.structure.nativegen.IrisNativeStructureDecision;
import art.arcane.iris.structure.nativegen.NativeStructureGenerationStatus;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.levelgen.structure.Structure;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import java.util.function.Predicate;

final class ModdedUnregisteredStructures {

    private ModdedUnregisteredStructures() {
    }

    static int print(CommandSourceStack source) {
        ServerLevel level = source.getLevel();
        Engine engine = IrisModdedCommands.engineFor(level);
        if (engine == null) {
            IrisModdedCommands.fail(source,
                    "This dimension is not generated by Iris, so it has no Iris structure eligibility report.");
            return 0;
        }
        try {
            List<ExcludedStructure> excluded = collect(source, level, engine);
            String dimension = level.dimension().identifier().toString();
            long unregistered = excluded.stream()
                    .filter((ExcludedStructure entry) -> entry.status() == ReportStatus.UNREGISTERED)
                    .count();
            long unplaced = excluded.stream()
                    .filter((ExcludedStructure entry) -> entry.status() == ReportStatus.UNPLACED)
                    .count();
            long hidden = excluded.size() - unregistered - unplaced;
            ModdedIrisLog.info("[Iris goto unregistered] {} structure candidate(s) excluded from /iris goto structure in {}",
                    excluded.size(), dimension);
            for (ExcludedStructure entry : excluded) {
                ModdedIrisLog.info("[Iris goto unregistered] [{}] {} - {}",
                        entry.status().label(), entry.key(), entry.reason());
            }
            ModdedIrisLog.info("[Iris goto unregistered] Inventory scope is the live registry, this pack's "
                    + "nativeStructures placements, and structureLoader editable resources. This is deterministic "
                    + "eligibility analysis and performs no chunk search; absent unmanaged datapack resources "
                    + "cannot be inferred after registry loading.");
            IrisModdedCommands.ok(source, "Iris wrote " + excluded.size() + " structure candidate(s) for "
                    + dimension + " to the server console (" + hidden + " excluded, "
                    + unregistered + " unregistered, " + unplaced + " unplaced).");
            return 1;
        } catch (Throwable error) {
            ModdedIrisLog.error("Iris failed to build the excluded structure report for {}",
                    level.dimension().identifier(), error);
            IrisModdedCommands.fail(source,
                    "Iris could not build the excluded structure report; see the server console.");
            return 0;
        }
    }

    static List<ExcludedStructure> collect(CommandSourceStack source, ServerLevel level, Engine engine) {
        boolean nativeGenerationEnabled =
                source.getServer().getWorldGenSettings().options().generateStructures();
        Set<String> reachableNativeKeys = StructureReachability.reachableKeys(engine);
        Registry<Structure> registry = source.getServer().registryAccess().lookupOrThrow(Registries.STRUCTURE);
        Map<String, ExcludedStructure> excluded = new TreeMap<>();
        Set<String> registeredKeys = new HashSet<>(registry.keySet().size());
        Set<String> eligibleRegisteredKeys = new HashSet<>(registry.keySet().size());
        for (Identifier identifier : registry.keySet()) {
            String key = identifier.toString();
            String normalizedKey = ModdedCommandSuggestions.normalizeKey(key);
            registeredKeys.add(normalizedKey);
            Optional<Holder.Reference<Structure>> holder = registry.get(identifier);
            if (holder.isEmpty()) {
                excluded.put(normalizedKey, new ExcludedStructure(ReportStatus.EXCLUDED,
                        key, "The live structure registry contains this key but has no bound structure holder."));
                continue;
            }
            IrisNativeStructureDecision decision = NativeStructureGenerationPolicy.resolve(engine, key, false);
            boolean nativePlacement = IrisStructureLocator.hasNativePlacement(engine, key);
            boolean locatableNativePlacement = nativePlacement
                    && IrisStructureLocator.hasLocatableNativePlacement(engine, key);
            boolean locatableEditableReplacement = !nativePlacement
                    && decision.status() == NativeStructureGenerationStatus.REPLACED_BY_IRIS
                    && IrisStructureLocator.hasLocatableEditablePlacement(engine, key);
            boolean reachable = reachableNativeKeys.contains(normalizedKey);
            if (ModdedCommandSuggestions.isEligibleRegisteredStructure(
                    decision, nativePlacement, locatableNativePlacement,
                    locatableEditableReplacement, reachable, nativeGenerationEnabled)) {
                eligibleRegisteredKeys.add(normalizedKey);
                continue;
            }
            ModdedLocateCommands.NativeStructureAvailability availability =
                    ModdedLocateCommands.nativeAvailability(source, level, engine, key, holder.get());
            String reason = ModdedLocateCommands.registeredStructureUnavailableMessage(
                    key, availability, decision, nativePlacement, locatableNativePlacement,
                    nativeGenerationEnabled, reachable);
            excluded.put(normalizedKey, new ExcludedStructure(ReportStatus.EXCLUDED, key, reason));
        }
        List<String> absentNativeKeys = missingConfiguredNativeKeys(
                IrisStructureLocator.placedKeys(engine), registeredKeys,
                (String key) -> IrisStructureLocator.hasNativePlacement(engine, key));
        for (String key : absentNativeKeys) {
            String normalizedKey = ModdedCommandSuggestions.normalizeKey(key);
            excluded.putIfAbsent(normalizedKey, new ExcludedStructure(ReportStatus.UNREGISTERED, key,
                    "Configured by an Iris nativeStructures placement, but absent from the live structure registry; "
                            + "install or enable the datapack or mod that provides this key."));
        }
        if (engine.getData().getStructureLoader() != null) {
            for (String key : engine.getData().getStructureLoader().getPossibleKeys()) {
                String normalizedKey = ModdedCommandSuggestions.normalizeKey(key);
                if (normalizedKey.isEmpty() || eligibleRegisteredKeys.contains(normalizedKey)
                        || excluded.containsKey(normalizedKey)) {
                    continue;
                }
                boolean registered = registeredKeys.contains(normalizedKey);
                boolean nativePlacement = IrisStructureLocator.hasNativePlacement(engine, key);
                boolean locatableEditable = IrisStructureLocator.hasLocatableEditablePlacement(engine, key);
                if (!registered && !nativePlacement && locatableEditable) {
                    continue;
                }
                boolean configured = IrisStructureLocator.hasEditablePlacement(engine, key);
                excluded.putIfAbsent(normalizedKey, new ExcludedStructure(
                        ReportStatus.UNPLACED, key.trim(), editableExclusionReason(configured)));
            }
        }
        return List.copyOf(excluded.values());
    }

    static List<String> missingConfiguredNativeKeys(
            Collection<String> placedKeys, Set<String> normalizedRegisteredKeys,
            Predicate<String> nativePlacement) {
        Map<String, String> missing = new TreeMap<>();
        for (String key : placedKeys) {
            String normalizedKey = ModdedCommandSuggestions.normalizeKey(key);
            if (!normalizedKey.isEmpty()
                    && !normalizedRegisteredKeys.contains(normalizedKey)
                    && nativePlacement.test(key)) {
                missing.putIfAbsent(normalizedKey, key.trim());
            }
        }
        return List.copyOf(missing.values());
    }

    static String editableExclusionReason(boolean configured) {
        if (!configured) {
            return "Editable Iris structure resource is loaded, but no biome, region, or dimension structure "
                    + "placement references it.";
        }
        return "Editable Iris structure resource is referenced by a placement, but every matching placement "
                + "has non-positive density or a Y band outside this world's height range.";
    }

    enum ReportStatus {
        EXCLUDED("excluded"),
        UNREGISTERED("unregistered"),
        UNPLACED("unplaced");

        private final String label;

        ReportStatus(String label) {
            this.label = label;
        }

        String label() {
            return label;
        }
    }

    record ExcludedStructure(ReportStatus status, String key, String reason) {
    }
}
