name: ${name}
version: ${version}
main: ${main}
load: STARTUP
authors: [ cyberpwn, NextdoorPsycho, Vatuu ]
website: volmit.com
description: More than a Dimension!
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - com.github.ben-manes.caffeine:caffeine:3.0.5
  - org.apache.commons:commons-lang3:3.12.0
  - io.timeandspace:smoothie-map:2.0.2
  - com.google.guava:guava:31.0.1-jre
  - com.google.code.gson:gson:2.8.9
  - org.zeroturnaround:zt-zip:1.14
  - it.unimi.dsi:fastutil:8.5.6
  - org.ow2.asm:asm:9.2
  - rhino:js:1.7R2
  - bsf:bsf:2.4.0
commands:
  iris:
    aliases: [ ir, irs ]
api-version: ${apiversion}
hotload-dependencies: false