name: ${name}
version: ${version}
main: ${main}
load: STARTUP
authors: [ cyberpwn, NextdoorPsycho ]
website: volmit.com
description: More than a Dimension!
libraries:
  - org.zeroturnaround:zt-zip:1.14
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.ow2.asm:asm:9.2
  - com.google.code.gson:gson:2.8.7
  - it.unimi.dsi:fastutil:8.5.4
  - com.google.guava:guava:30.1.1-jre
  - bsf:bsf:2.4.0
  - rhino:js:1.7R2
commands:
  iris:
    aliases: [ ir, irs ]
api-version: ${apiversion}
hotload-dependencies: false