package art.arcane.iris.generation.hydrology;

public enum HydrologyCandidateRejection {
    NO_LEGAL_OUTLET,
    NO_DRAINAGE_PATH,
    CONFINED_NO_OUTLET,
    ROUTE_LIMIT,
    COURSE_TOO_SHORT,
    SOURCE_QUOTA,
    SOURCE_SPACING,
    OUTLET_LIMIT,
    OUTLET_LEVEL,
    CAVE_CONTAINMENT,
    VOLUME_LIMIT,
    SURFACE_HEAD_RANGE,
    SURFACE_HEAD_DISTRIBUTION,
    SURFACE_EXPOSURE,
    SURFACE_DROP_UNSUPPORTED,
    SURFACE_CORRIDOR_UNSUPPORTED,
    SURFACE_TRANSITION_UNSUPPORTED,
    SURFACE_SEGMENT_UNSUPPORTED,
    SURFACE_SINKHOLE_CLEARANCE,
    SURFACE_SHAPE_UNSUPPORTED,
    SURFACE_MOUTH_DISCONNECTED,
    SURFACE_WATER_CONTAINMENT,
    SURFACE_BANK_BUDGET,
    POLICY_EXCLUDED;
}
