package art.arcane.iris.purity;

import art.arcane.iris.pack.schema.annotation.Snippet;
import org.junit.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

import java.io.File;
import java.lang.annotation.Annotation;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Modifier;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * Structural purity gate for everything Gson touches in a pack.
 * <p>
 * The text ratchet in {@code core/build.gradle} ('bukkitPurityRatchet') greps for the string
 * "org.bukkit" per file. It cannot see the two failure shapes that actually break the modded
 * loaders, because both are produced by the compiler rather than written by hand:
 * <ul>
 *   <li>Lombok generating {@code equals}/{@code hashCode}/{@code toString} against a hand-written
 *       getter that shadows the field accessor and returns a resolved Bukkit type, e.g.
 *       {@code IrisBiome.getDerivative() -> org.bukkit.block.Biome}. The generated bytecode then
 *       references org.bukkit even though the field is a String. Closed globally by
 *       {@code lombok.config}: {@code equalsAndHashCode.doNotUseGetters} + {@code toString.doNotUseGetters}.</li>
 *   <li>A raw Bukkit-typed field. Gson walks {@code getDeclaredFields()} and the JVM resolves every
 *       field type there, so one such field takes the whole pack type down.</li>
 * </ul>
 * So this test loads each pack type on a classloader where {@code org.bukkit.**} does not exist and
 * runs the Gson-shaped operations against it.
 * <p>
 * <b>Observed pre-fix failures (WP4 baseline):</b> {@code IrisBiome} and {@code IrisEffect}
 * (getter-shadowed equals/hashCode/toString), {@code IrisBiomeCustomSpawn} and
 * {@code IrisBiomeCustomParticle} (same shape), {@code TileData} (raw {@code org.bukkit.Material}
 * field plus a {@code toString} routed through {@code KeyedType} -> {@code NamespacedKey}),
 * {@code IrisVanillaLootTable} (raw {@code org.bukkit.loot.LootTable} field),
 * {@code IrisVillagerTrade} (three raw {@code org.bukkit.inventory.ItemStack} fields; class
 * deleted) and {@code Particles} (Bukkit registry lookups in a static initializer).
 * <p>
 * <b>Deliberately not asserted:</b> method and constructor descriptors. These classes legitimately
 * expose a Bukkit-typed edge that only the Bukkit adapter calls - {@code IrisEntity.spawn(Engine,
 * Location)}, {@code IrisLoot.get(...) -> ItemStack}, {@code IrisObjectRotation.rotate(BlockData,
 * ...)}, {@code TileData.toBukkit(Block)} and ~60 more. Method descriptors are resolved at
 * invocation, never at class load, field walk or equals/hashCode/toString, so they are not a modded
 * boot hazard. Fields and supertypes are, and both are asserted hard below.
 */
public class PackTypeBukkitPurityGateTest {
    private static final String SNIPPET_DESCRIPTOR = "Lart/arcane/iris/pack/schema/annotation/Snippet;";
    private static final String BUKKIT_INTERNAL_PREFIX = "org/bukkit/";
    /** See {@link #theGateStillCatchesAClassThatNeedsBukkit()}. */
    private static final String BUKKIT_DEPENDENT_CANARY = "art.arcane.iris.structure.object.IrisObjectRotation$Faces";
    private static final String IRIS_PACKAGE = "art/arcane/iris";
    private static final String IRIS_DATA = "art.arcane.iris.pack.loading.IrisData";

    /**
     * Every type handed to {@code registerLoader} in {@code IrisData.hotloaded()} - i.e. every root
     * type Gson deserializes from a pack. Kept literal on purpose; {@link
     * #registeredRootListMatchesIrisData()} fails if the compiled registrations drift away from it.
     */
    private static final List<String> GSON_REGISTERED_ROOTS = List.of(
            "art.arcane.iris.world.loot.IrisLootTable",
            "art.arcane.iris.world.entity.IrisSpawner",
            "art.arcane.iris.world.entity.IrisEntity",
            "art.arcane.iris.generation.terrain.IrisRegion",
            "art.arcane.iris.generation.biome.IrisBiome",
            "art.arcane.iris.pack.mod.IrisMod",
            "art.arcane.iris.generation.terrain.IrisDimension",
            "art.arcane.iris.generation.noise.IrisGenerator",
            "art.arcane.iris.world.entity.IrisMarker",
            "art.arcane.iris.generation.block.IrisBlockData",
            "art.arcane.iris.generation.noise.IrisExpression",
            "art.arcane.iris.structure.object.IrisObject",
            "art.arcane.iris.generation.image.IrisImage",
            "art.arcane.iris.generation.image.IrisImageMap",
            "art.arcane.iris.structure.object.matter.IrisMatterObject",
            "art.arcane.iris.structure.placement.IrisStructure",
            "art.arcane.iris.structure.jigsaw.IrisJigsawPool",
            "art.arcane.iris.structure.jigsaw.IrisJigsawPiece");

    /**
     * Types reachable from a pack that are not roots and carry no {@code @Snippet}, but are
     * deserialized/serialized all the same (object tile payloads, vanilla loot table adapters).
     */
    private static final List<String> ADDITIONAL_PACK_TYPES = List.of(
            "art.arcane.iris.generation.block.TileData",
            "art.arcane.iris.generation.block.LegacyTileData",
            "art.arcane.iris.world.loot.IrisVanillaLootTable");

    /**
     * Bukkit-registry constant holders that a core pack type references, so their class initializer
     * runs on the modded loaders too. {@code Particles} is statically imported by {@code IrisEntity}.
     * ({@code Materials} and {@code Attributes} have the same shape but are only reachable from the
     * Bukkit adapter, so they stay out of the gate.)
     */
    private static final List<String> BUKKIT_STATIC_HOLDERS = List.of(
            "art.arcane.iris.platform.bukkit.registry.Particles");

    @Test
    public void theGateActuallyHidesBukkit() throws Exception {
        ClassLoader app = getClass().getClassLoader();
        assertNotNull("paper-api must be on the test classpath for this gate to mean anything",
                Class.forName("org.bukkit.Material", false, app));

        BukkitHidingClassLoader hiding = new BukkitHidingClassLoader(app);
        assertThrows("the hiding loader must refuse org.bukkit even though paper-api is present",
                ClassNotFoundException.class,
                () -> Class.forName("org.bukkit.Material", false, hiding));
        assertThrows(ClassNotFoundException.class,
                () -> Class.forName("org.bukkit.Bukkit", false, hiding));

        Class<?> selfDefined = Class.forName("art.arcane.iris.pack.value.IrisPosition", false, hiding);
        assertEquals("iris classes must be defined by the hiding loader, not delegated to the parent",
                hiding, selfDefined.getClassLoader());
    }

    @Test
    public void registeredRootListMatchesIrisData() throws Exception {
        byte[] bytes = BukkitHidingClassLoader.readClassBytes(getClass().getClassLoader(), IRIS_DATA);
        assertNotNull("no class bytes for " + IRIS_DATA, bytes);

        Set<String> registered = new TreeSet<>();
        new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9) {
            @Override
            public MethodVisitor visitMethod(
                    int access,
                    String name,
                    String descriptor,
                    String signature,
                    String[] exceptions
            ) {
                return new MethodVisitor(Opcodes.ASM9) {
                    private String pendingRegistrant;

                    @Override
                    public void visitLdcInsn(Object value) {
                        if (value instanceof Type type && type.getSort() == Type.OBJECT) {
                            pendingRegistrant = type.getClassName();
                        }
                    }

                    @Override
                    public void visitMethodInsn(
                            int opcode,
                            String owner,
                            String methodName,
                            String methodDescriptor,
                            boolean isInterface
                    ) {
                        if ("registerLoader".equals(methodName) && pendingRegistrant != null) {
                            registered.add(pendingRegistrant.substring(pendingRegistrant.lastIndexOf('.') + 1));
                        }
                        pendingRegistrant = null;
                    }
                };
            }
        }, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);

        Set<String> inTest = new TreeSet<>();
        for (String name : GSON_REGISTERED_ROOTS) {
            inTest.add(name.substring(name.lastIndexOf('.') + 1));
        }
        assertEquals("IrisData registers a different set of pack roots than this gate covers - "
                + "add the new type to GSON_REGISTERED_ROOTS", inTest, registered);
    }

    @Test
    public void bukkitStaticHoldersInitializeWithoutBukkit() {
        BukkitHidingClassLoader hiding = new BukkitHidingClassLoader(getClass().getClassLoader());
        List<String> failures = new ArrayList<>();
        for (String name : BUKKIT_STATIC_HOLDERS) {
            try {
                Class.forName(name, true, hiding);
            } catch (Throwable e) {
                if (mentionsBukkit(e)) {
                    failures.add(name + "#<clinit>: " + describe(e));
                }
            }
        }
        assertPure(failures);
    }

    @Test
    public void packTypesLoadAndBehaveWithoutBukkit() throws Exception {
        BukkitHidingClassLoader hiding = new BukkitHidingClassLoader(getClass().getClassLoader());
        List<String> gateTypes = gateTypes();
        assertTrue("expected the @Snippet scan to find the pack snippet types, found only "
                + gateTypes.size(), gateTypes.size() > 60);

        List<String> failures = new ArrayList<>();
        List<String> skipped = new ArrayList<>();

        for (String name : gateTypes) {
            Class<?> type;
            try {
                type = Class.forName(name, true, hiding);
            } catch (Throwable e) {
                record(failures, skipped, name + "#<clinit>", e);
                continue;
            }

            // Gson step 1: walk the declared fields and their annotations. Both resolve types.
            Field[] declared;
            try {
                declared = type.getDeclaredFields();
                for (Field field : declared) {
                    field.getType();
                    // Gson resolves the generic type of every field it walks, and the type arguments a
                    // descriptor erased are resolved there and nowhere else - a KList<BlockData> field is as
                    // fatal as a raw BlockData one. Static and transient fields are excluded before Gson ever
                    // asks for their generic type, so they are excluded here too.
                    int modifiers = field.getModifiers();
                    if (!Modifier.isStatic(modifiers) && !Modifier.isTransient(modifiers)) {
                        field.getGenericType();
                    }
                    for (Annotation annotation : field.getDeclaredAnnotations()) {
                        annotation.annotationType();
                    }
                }
                for (Annotation annotation : type.getDeclaredAnnotations()) {
                    annotation.annotationType();
                }
            } catch (Throwable e) {
                record(failures, skipped, name + "#getDeclaredFields", e);
                continue;
            }

            // Gson step 2: construct via the no-arg constructor where one exists.
            Constructor<?> noArg;
            try {
                noArg = type.getDeclaredConstructor();
            } catch (NoSuchMethodException e) {
                noArg = null;
            } catch (Throwable e) {
                record(failures, skipped, name + "#getDeclaredConstructor", e);
                continue;
            }
            if (noArg == null) {
                continue;
            }

            Object first;
            Object second;
            try {
                noArg.setAccessible(true);
                first = noArg.newInstance();
                second = noArg.newInstance();
            } catch (Throwable e) {
                record(failures, skipped, name + "#<init>", e);
                continue;
            }

            // Lombok step: the generated members that used to bake in Bukkit getters.
            try {
                first.equals(second);
            } catch (Throwable e) {
                record(failures, skipped, name + "#equals", e);
            }
            try {
                first.hashCode();
                second.hashCode();
            } catch (Throwable e) {
                record(failures, skipped, name + "#hashCode", e);
            }
            try {
                first.toString();
            } catch (Throwable e) {
                record(failures, skipped, name + "#toString", e);
            }
        }

        // A failure that does not name org.bukkit is still a failure. Every pack type must load, walk and
        // compare headlessly with no server at all - that is what a mod loader's dedicated server does, and
        // it is what the studio and every test does too. Nothing on this list is tolerated: the whole gate
        // set currently gets through with zero skips, so a skip means new code broke something.
        assertTrue("Bukkit purity gate: " + skipped.size() + " pack member(s) failed for a non-Bukkit reason. "
                        + "These still cannot be Gson-walked on a headless server - fix them or explain the "
                        + "exemption here:" + join(skipped),
                skipped.isEmpty());
        assertPure(failures);
    }

    /**
     * Negative control. Every other assertion here passes when the gate is working <em>and</em> when it is
     * silently broken - a classloader that quietly delegates org.bukkit to the parent, a
     * {@link #mentionsBukkit(Throwable)} that stopped matching, a class scan that found nothing. This test
     * fails in exactly that case, by pointing the machinery at a class that provably cannot initialize
     * without Bukkit.
     * <p>
     * {@code IrisObjectRotation$Faces} is a private lazy holder whose initializer reads
     * {@code org.bukkit.block.BlockFace} constants. It is deliberately <em>not</em> in the gate set: the holder
     * exists precisely so that the Bukkit-edge rotation methods can touch BlockFace without dragging it into
     * the enclosing pack type's own initializer. That makes it the ideal control - a real class, in the pack
     * package, that the gate must be able to catch.
     */
    @Test
    public void theGateStillCatchesAClassThatNeedsBukkit() {
        BukkitHidingClassLoader hiding = new BukkitHidingClassLoader(getClass().getClassLoader());
        List<String> failures = new ArrayList<>();
        List<String> skipped = new ArrayList<>();

        // The assertion has to live outside the catch: this method's own catch is a catch(Throwable), and an
        // AssertionError raised inside it would be swallowed and then recorded as a Bukkit failure, because the
        // failure message itself names org.bukkit. The control would pass in the one case it exists to catch.
        Throwable error = null;
        try {
            Class.forName(BUKKIT_DEPENDENT_CANARY, true, hiding);
        } catch (Throwable e) {
            error = e;
        }

        assertNotNull(BUKKIT_DEPENDENT_CANARY + " initialized with org.bukkit hidden - the gate is not hiding "
                + "Bukkit any more, so every other assertion in this class is vacuous", error);
        record(failures, skipped, BUKKIT_DEPENDENT_CANARY + "#<clinit>", error);

        assertTrue("the canary failed for a non-Bukkit reason, so the gate would no longer recognize a real "
                        + "Bukkit dependency as one:" + join(skipped), skipped.isEmpty());
        assertEquals("the canary must be recorded as a Bukkit purity failure", 1, failures.size());
    }

    /**
     * Second negative control, for the generic-signature half of
     * {@link #packTypeFieldsAndSupertypesDeclareNoBukkit()}. Every pack type currently passes that check, so a
     * parser regression that stopped reading the {@code Signature} attribute would look exactly like success.
     * {@code IrisBiome#derivativeResolved} is the reference case: descriptor erased to a bare AtomicCache, type
     * argument {@code org.bukkit.block.Biome}, exempt from the check only because it is transient - which is what
     * every resolved-value cache in a pack type looks like.
     */
    @Test
    public void theGenericSignatureScanSeesWhatTheDescriptorErased() throws Exception {
        byte[] bytes = BukkitHidingClassLoader.readClassBytes(getClass().getClassLoader(),
                "art.arcane.iris.generation.biome.IrisBiome");
        assertNotNull("no class bytes for IrisBiome", bytes);

        ClassFileFacts.DeclaredField cache = null;
        for (ClassFileFacts.DeclaredField field : ClassFileFacts.read(bytes).fields()) {
            if (field.name().equals("derivativeResolved")) {
                cache = field;
                break;
            }
        }

        assertNotNull("IrisBiome#derivativeResolved is the reference case for the generic-signature scan - "
                + "if it was renamed, point this test at another AtomicCache of a Bukkit type", cache);
        assertFalse("the erased descriptor cannot name the Bukkit type argument, which is the whole reason the "
                + "signature is read: " + cache.descriptor(), cache.descriptor().contains(BUKKIT_INTERNAL_PREFIX));
        assertNotNull("no Signature attribute was read for a generic field - the scan is vacuous", cache.signature());
        assertTrue("the Signature attribute must name the erased Bukkit type argument, got " + cache.signature(),
                cache.signature().contains(BUKKIT_INTERNAL_PREFIX));
        assertTrue("this field is exempt only because it is transient - Gson never resolves its generic type",
                cache.isTransient());
    }

    private static String join(List<String> lines) {
        StringBuilder out = new StringBuilder();
        for (String line : lines) {
            out.append("\n  ").append(line);
        }
        return out.toString();
    }

    @Test
    public void packTypeFieldsAndSupertypesDeclareNoBukkit() throws Exception {
        ClassLoader app = getClass().getClassLoader();
        List<String> failures = new ArrayList<>();

        for (String name : gateTypes()) {
            byte[] bytes = BukkitHidingClassLoader.readClassBytes(app, name);
            assertNotNull("no class bytes for " + name, bytes);
            ClassFileFacts facts = ClassFileFacts.read(bytes);

            if (facts.superName() != null && facts.superName().startsWith(BUKKIT_INTERNAL_PREFIX)) {
                failures.add(name + ": extends " + facts.superName());
            }
            for (String iface : facts.interfaceNames()) {
                if (iface.startsWith(BUKKIT_INTERNAL_PREFIX)) {
                    failures.add(name + ": implements " + iface);
                }
            }
            for (ClassFileFacts.DeclaredField field : facts.fields()) {
                if (field.isStatic()) {
                    continue;
                }
                // The raw descriptor is resolved by getDeclaredFields() for every declared field, transient
                // included, so it must be Bukkit-free unconditionally.
                if (field.descriptor().contains(BUKKIT_INTERNAL_PREFIX)) {
                    failures.add(name + "#field " + field.name() + ": " + field.descriptor()
                            + " (store the namespaced key as a String and resolve it at the Bukkit edge)");
                }
                // The generic signature carries what the descriptor erased. Gson resolves it through
                // getGenericType(), but only for the fields it walks - transient fields are excluded first.
                if (!field.isTransient() && field.signature() != null
                        && field.signature().contains(BUKKIT_INTERNAL_PREFIX)) {
                    failures.add(name + "#field " + field.name() + ": " + field.signature()
                            + " (a Bukkit type argument is resolved by Gson's getGenericType() even though the "
                            + "descriptor erased it - hold the neutral type, or mark the field transient if it is a cache)");
                }
            }
        }

        assertPure(failures);
    }

    private static void record(List<String> failures, List<String> skipped, String member, Throwable e) {
        if (mentionsBukkit(e)) {
            failures.add(member + ": " + describe(e));
        } else {
            skipped.add(member + ": " + describe(e));
        }
    }

    private static void assertPure(List<String> failures) {
        if (failures.isEmpty()) {
            return;
        }
        StringBuilder message = new StringBuilder("Bukkit purity gate failed on ")
                .append(failures.size())
                .append(" member(s) - these cannot load on Fabric/Forge/NeoForge:");
        for (String failure : failures) {
            message.append("\n  ").append(failure);
        }
        fail(message.toString());
    }

    /**
     * True when anything in the throwable chain names org.bukkit. That is the discriminator between
     * "this type is not modded-safe" and "the default instance of this type happens to be awkward to
     * build in a unit test", which keeps the gate from becoming a general instantiability test.
     */
    private static boolean mentionsBukkit(Throwable error) {
        Set<Throwable> seen = Collections.newSetFromMap(new IdentityHashMap<>());
        for (Throwable current = error; current != null && seen.add(current); current = current.getCause()) {
            String message = current.getMessage();
            if (message != null) {
                String normalized = message.replace('/', '.').toLowerCase(Locale.ROOT);
                if (normalized.contains("org.bukkit")) {
                    return true;
                }
            }
            for (Throwable suppressed : current.getSuppressed()) {
                if (mentionsBukkit(suppressed)) {
                    return true;
                }
            }
        }
        return false;
    }

    private static String describe(Throwable error) {
        Throwable root = error;
        if (root instanceof InvocationTargetException && root.getCause() != null) {
            root = root.getCause();
        }
        StringBuilder out = new StringBuilder(root.getClass().getName());
        if (root.getMessage() != null) {
            out.append(": ").append(root.getMessage());
        }
        Throwable cause = root.getCause();
        if (cause != null && cause != root) {
            out.append(" <- ").append(cause.getClass().getSimpleName());
            if (cause.getMessage() != null) {
                out.append(": ").append(cause.getMessage());
            }
        }
        return out.toString();
    }

    /** The Gson roots, the extra pack-reachable types, and every {@code @Snippet} class. */
    private static List<String> gateTypes() throws Exception {
        Set<String> types = new LinkedHashSet<>(GSON_REGISTERED_ROOTS);
        types.addAll(ADDITIONAL_PACK_TYPES);
        types.addAll(snippetTypes());
        return new ArrayList<>(types);
    }

    private static List<String> snippetTypes() throws Exception {
        ClassLoader app = PackTypeBukkitPurityGateTest.class.getClassLoader();
        List<String> snippets = new ArrayList<>();
        for (String candidate : classNamesUnder(IRIS_PACKAGE)) {
            if (candidate.indexOf('$') >= 0) {
                continue;
            }
            byte[] bytes = BukkitHidingClassLoader.readClassBytes(app, candidate);
            if (bytes == null) {
                continue;
            }
            if (ClassFileFacts.read(bytes).hasClassAnnotation(SNIPPET_DESCRIPTOR)) {
                snippets.add(candidate);
            }
        }
        Collections.sort(snippets);
        assertFalse("@Snippet class scan found nothing - is " + Snippet.class.getName()
                + " still runtime-retained?", snippets.isEmpty());
        return snippets;
    }

    private static List<String> classNamesUnder(String packageInternalName) throws Exception {
        assertNotNull("no code source for " + Snippet.class.getName() + " - cannot enumerate pack types",
                Snippet.class.getProtectionDomain().getCodeSource());
        URL location = Snippet.class.getProtectionDomain().getCodeSource().getLocation();
        Path root = Paths.get(location.toURI());
        List<String> names = new ArrayList<>();

        if (Files.isDirectory(root)) {
            Path directory = root.resolve(packageInternalName);
            if (!Files.isDirectory(directory)) {
                return names;
            }
            try (Stream<Path> walk = Files.walk(directory)) {
                walk.filter(path -> path.toString().endsWith(".class")).forEach(path -> {
                    String relative = root.relativize(path).toString().replace(File.separatorChar, '/');
                    names.add(relative.substring(0, relative.length() - ".class".length()).replace('/', '.'));
                });
            }
            return names;
        }

        try (ZipFile zip = new ZipFile(root.toFile())) {
            zip.stream()
                    .map(ZipEntry::getName)
                    .filter(entry -> entry.startsWith(packageInternalName + "/") && entry.endsWith(".class"))
                    .forEach(entry -> names.add(
                            entry.substring(0, entry.length() - ".class".length()).replace('/', '.')));
        }
        return names;
    }
}
