package art.arcane.iris.structure.nativegen;

import art.arcane.iris.structure.jigsaw.IrisJigsawConfiguration;

import art.arcane.volmlib.util.documentation.Description;
import art.arcane.iris.pack.schema.annotation.MinNumber;
import art.arcane.iris.pack.schema.annotation.RegistryListVanillaStructure;
import art.arcane.iris.pack.schema.annotation.Required;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Data
@Description("A live vanilla, datapack, or modded structure generated by Minecraft at an Iris-controlled placement.")
public class IrisNativeStructure {
    @Required
    @RegistryListVanillaStructure
    @Description("Registered structure key. The source retains its native generator, pieces, templates, processors, entities, markers, and data.")
    private String structure = "";

    @MinNumber(1)
    @Description("Relative selection weight when a placement offers multiple native structure sources.")
    private int weight = 1;

    @Description("Optional jigsaw-only assembly overrides. Null preserves the complete registered structure definition.")
    private IrisJigsawConfiguration jigsaw = null;
}
