/*
 * Iris is a World Generator for Minecraft Servers
 * Copyright (c) 2026 Arcane Arts (Volmit Software)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package art.arcane.iris.modded.api;

import art.arcane.iris.world.WorldMaintenance;
import art.arcane.iris.generation.runtime.Engine;
import art.arcane.iris.generation.runtime.EngineLifecycleTasks;
import art.arcane.iris.modded.IrisModdedChunkGenerator;
import art.arcane.iris.modded.command.ModdedPregenJob;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.chunk.ChunkGenerator;

/**
 * Entry point for mods integrating with Iris on Fabric, Forge and NeoForge.
 * <p>
 * Everything here is static and null-tolerant: a null or non-Iris {@link ServerLevel} produces false, null, or a
 * no-op rather than an exception, so a caller never has to pre-check whether a level is generated by Iris.
 * <p>
 * <b>Threading.</b> {@link #isIrisLevel(ServerLevel)}, {@link #isStudioLevel(ServerLevel)} and
 * {@link #getEngine(ServerLevel)} read the level's chunk generator reference and are safe from any thread once
 * the level is loaded. The mantle accessors are safe off the server thread but touch engine storage - see their
 * own notes. {@link #pregenerate(ServerLevel, int)} and {@link #registerProvider(ModdedDataProvider)} mutate
 * global state and belong on the server thread, during mod setup or from a command.
 * <p>
 * <b>Stability.</b> This class and the {@code Modded*} types beside it are the intended integration surface. The
 * types they expose from {@code art.arcane.iris.generation.runtime.*} and {@code art.arcane.iris.pack.*} - notably
 * {@link Engine} - are internal to Iris and change without a deprecation cycle. Treat {@link Engine} as an opaque
 * token to hand back to Iris, and prefer the wrappers here over reaching into it.
 *
 * @see ModdedDataProvider for supplying custom blocks, items and entities to the generator
 */
public final class IrisModdedAPI {
    private IrisModdedAPI() {
    }

    /**
     * Whether {@code level}'s chunk generator is an Iris generator. False for null and for every vanilla or
     * third-party generated level. The cheapest available Iris check.
     */
    public static boolean isIrisLevel(ServerLevel level) {
        if (level == null) {
            return false;
        }
        return level.getChunkSource().getGenerator() instanceof IrisModdedChunkGenerator;
    }

    /**
     * Whether {@code level} is an Iris studio level - a throwaway world opened for pack authoring, which is
     * deleted on shutdown. Persist nothing against one. False for null and for non-Iris levels.
     */
    public static boolean isStudioLevel(ServerLevel level) {
        Engine engine = getEngine(level);
        return engine != null && engine.isStudio();
    }

    /**
     * The Iris engine driving {@code level}, or null when the level is null, is not Iris-generated, or its engine
     * is not currently available - during shutdown, or while the generator is still binding.
     * <p>
     * Never cached: resolve per use. Reloading a pack or unloading the level replaces the engine, and a stale
     * reference goes inert. {@link Engine} is internal to Iris; see the stability note on this class.
     */
    public static Engine getEngine(ServerLevel level) {
        if (level == null) {
            return null;
        }
        ChunkGenerator generator = level.getChunkSource().getGenerator();
        if (!(generator instanceof IrisModdedChunkGenerator irisGenerator)) {
            return null;
        }
        try {
            return irisGenerator.commandEngine();
        } catch (Throwable error) {
            return null;
        }
    }

    /**
     * Starts a cached, asynchronous pregeneration of {@code radiusBlocks} around the world origin.
     * Equivalent to {@code pregenerate(level, radiusBlocks, 0, 0, false, true)}.
     */
    public static boolean pregenerate(ServerLevel level, int radiusBlocks) {
        return pregenerate(level, radiusBlocks, 0, 0, false, true);
    }

    /**
     * Starts a pregeneration job over a square region.
     * <p>
     * Returns as soon as the job is queued; progress is reported through Iris's own logging and boss bar, not to
     * the caller. Only one job runs server-wide, so this returns false if one is already active. Call on the
     * server thread.
     *
     * @param radiusBlocks half-extent of the square in blocks, measured from the centre
     * @param sync         write chunks synchronously; slower but avoids the async write queue
     * @param cached       reuse and update the on-disk pregeneration cache so an interrupted job resumes instead of
     *                     regenerating
     * @return false when {@code level} is not Iris-generated or another pregeneration job is already running
     */
    public static boolean pregenerate(ServerLevel level, int radiusBlocks, int centerBlockX, int centerBlockZ, boolean sync, boolean cached) {
        Engine engine = getEngine(level);
        if (engine == null) {
            return false;
        }
        return ModdedPregenJob.start(level.getServer(), level, engine, radiusBlocks, centerBlockX, centerBlockZ, false, sync, cached);
    }

    /**
     * Reads a mantle value of {@code type} at world coordinates.
     * <p>
     * The mantle is Iris's own per-block sidecar storage, independent of chunk NBT, and it is how Iris carries
     * data that must survive between generation stages. Coordinates are world-space: {@code y} is translated by
     * the engine's minimum height internally.
     * <p>
     * Returns null when the level is not Iris-generated, no mantle region exists for that column yet - reads
     * never create or load one - or nothing of {@code type} is stored there. A {@code y} outside the engine's
     * height range reads as null rather than throwing.
     *
     * A closing or closed engine refuses the operation quietly (null / no-op) instead of racing its shutdown.
     */
    public static <T> T getMantleData(ServerLevel level, int x, int y, int z, Class<T> type) {
        Engine engine = getEngine(level);
        if (engine == null) {
            return null;
        }
        // Lease-gated so the engine shutdown drain covers this public accessor; a mantle
        // mid-close refuses the lease instead of racing the region flush.
        return EngineLifecycleTasks.call(engine, "modded_api_mantle_get",
                () -> engine.getMantle().getMantle().get(x, y - engine.getMinHeight(), z, type), null);
    }

    /**
     * Writes a mantle value at world coordinates, replacing any previous value of the same type there.
     * <p>
     * Unlike {@link #getMantleData(ServerLevel, int, int, int, Class)}, a write creates the mantle region if it
     * does not exist, which can touch disk - do not call it per block in a tick loop from the server thread. A
     * null {@code data}, a non-Iris level, or a {@code y} outside the engine's height range is a silent no-op;
     * remove values with {@link #deleteMantleData(ServerLevel, int, int, int, Class)}.
     * <p>
     * Values written under a custom type are discarded when Iris trims a mantle region unless the type is
     * declared with {@link #retainMantleDataForSlice(Class)}.
     *
     * A closing or closed engine refuses the operation quietly (null / no-op) instead of racing its shutdown.
     */
    public static <T> void setMantleData(ServerLevel level, int x, int y, int z, T data) {
        Engine engine = getEngine(level);
        if (engine == null || data == null) {
            return;
        }
        EngineLifecycleTasks.run(engine, "modded_api_mantle_set",
                () -> engine.getMantle().getMantle().set(x, y - engine.getMinHeight(), z, data));
    }

    /**
     * Removes any mantle value of {@code type} at world coordinates. A non-Iris level or an out-of-range
     * {@code y} is a silent no-op. Like a write, this creates the mantle region if it is absent.
     *
     * A closing or closed engine refuses the operation quietly (null / no-op) instead of racing its shutdown.
     */
    public static <T> void deleteMantleData(ServerLevel level, int x, int y, int z, Class<T> type) {
        Engine engine = getEngine(level);
        if (engine == null) {
            return;
        }
        EngineLifecycleTasks.run(engine, "modded_api_mantle_delete",
                () -> engine.getMantle().getMantle().remove(x, y - engine.getMinHeight(), z, type));
    }

    /**
     * Declares that mantle slices of {@code sliceType} must be kept rather than discarded.
     * <p>
     * Iris drops slices it does not need once a region's generation data has served its purpose - both the
     * normal per-chunk trim and pregeneration's forced cleanup honor this registry. Any type a mod writes
     * with {@link #setMantleData(ServerLevel, int, int, int, Object)} and expects to read back later must be
     * declared here first. Registration is by canonical class name, process-wide across every Iris world, and
     * cannot be undone - declare it once during mod setup. A null {@code sliceType} is ignored, and the
     * block-state slice can never be retained.
     * <p>
     * Retained data lives for the world's lifetime: it persists into the mantle region files and unloads
     * with them, so region files grow with everything you retain. The mod owns the cleanup - call
     * {@code deleteMantleData} when a value is no longer needed.
     */
    public static void retainMantleDataForSlice(Class<?> sliceType) {
        if (sliceType == null) {
            return;
        }
        WorldMaintenance.retainMantleDataForSlice(sliceType.getCanonicalName());
    }

    /**
     * Registers a custom content provider imperatively, for mods that would rather call Iris than ship a
     * {@link java.util.ServiceLoader} entry.
     * <p>
     * Providers are keyed by {@link ModdedDataProvider#modId()}; a second registration under an id already present
     * is logged and ignored. {@link ModdedDataProvider#init()} runs during this call, and a throwable it raises is
     * logged rather than propagated. A null {@code provider} is ignored.
     * <p>
     * Ordering matters: Iris only consults providers registered before a pack resolves the block in question, so
     * register during mod setup. Registering after Iris's own {@link java.util.ServiceLoader} discovery is
     * supported; registering after a world has generated is not - blocks already resolved are not revisited.
     */
    public static void registerProvider(ModdedDataProvider provider) {
        ModdedCustomContentRegistry.register(provider);
    }

    /**
     * Maps a custom {@code namespace:key} onto a fixed vanilla block state, for mods that only need a static alias
     * and no provider class.
     * <p>
     * {@code state} is a block state string in the same syntax packs use, for example
     * {@code minecraft:oak_log[axis=y]}, and is parsed immediately: an unparseable state or an invalid identifier
     * is logged and the registration is dropped, so a typo shows up at startup rather than as missing blocks.
     * Aliases take precedence over provider lookups for the same key. Null arguments are ignored.
     */
    public static void registerCustomBlockData(String namespace, String key, String state) {
        ModdedCustomContentRegistry.registerCustomBlockData(namespace, key, state);
    }
}
