package art.arcane.iris.localization;

import art.arcane.volmlib.util.diagnostics.BukkitDebugMessages;
import art.arcane.volmlib.util.director.DirectorMessages;
import art.arcane.volmlib.util.localization.BukkitLanguageMessages;
import art.arcane.volmlib.util.localization.MessageCatalog;
import art.arcane.volmlib.util.localization.MessageKey;
import art.arcane.volmlib.util.localization.TextKey;
import art.arcane.volmlib.util.localization.VolmitLocales;

import java.util.List;
import java.util.ServiceLoader;

public final class IrisMessages {
    public static final TextKey PREGEN_ALREADY_RUNNING = TextKey.of(
            "iris.modded.irismoddedcommands.pregeneration_task_is_already_running_stop_it_first_with_iris",
            "A pregeneration task is already running. Stop it first with /iris pregen stop."
    );

    public static final TextKey COMMAND_PERMISSION_DENIED = TextKey.of(
            "iris.command.permission_denied",
            "You lack the permission '{permission}'"
    );
    public static final TextKey COMMAND_UNKNOWN = TextKey.of(
            "iris.command.unknown",
            "Unknown Iris command"
    );
    public static final TextKey COMMAND_PLAYER_ONLY = TextKey.of(
            "iris.command.player_only",
            "This command can only be used by players."
    );
    public static final TextKey COMMAND_IRIS_WORLD_REQUIRED = TextKey.of(
            "iris.command.iris_world_required",
            "This dimension is not generated by Iris."
    );
    public static final TextKey COMMAND_RELOAD_SUCCESS = TextKey.of(
            "iris.command.reload.success",
            "Hotloaded settings and locale {locale}."
    );
    public static final TextKey COMMAND_RELOAD_FAILED = TextKey.of(
            "iris.command.reload.failed",
            "Settings were reloaded, but locale {locale} was rejected; continuing with {activeLocale}."
    );
    public static final TextKey MODDED_HELP_UNKNOWN_SECTION = TextKey.of(
            "iris.modded.help.unknown_section",
            "Unknown Iris help section: {section}"
    );
    public static final TextKey MODDED_HELP_BACK_HOVER = TextKey.of(
            "iris.modded.help.back_hover",
            "Return to {parent}."
    );
    public static final TextKey MODDED_HELP_COMMAND_PARAMETER = TextKey.of(
            "iris.modded.help.command_parameter",
            "Command parameter"
    );
    public static final TextKey MODDED_HELP_BRIGADIER_TEXT = TextKey.of(
            "iris.modded.help.brigadier_text",
            "This parameter is read as text by Brigadier."
    );
    public static final TextKey MODDED_HELP_OPERATOR_NOTICE = TextKey.of(
            "iris.modded.help.operator_notice",
            "Iris commands need operator permission (level 2)."
    );
    public static final TextKey MODDED_HELP_OPERATOR_INSTRUCTION = TextKey.of(
            "iris.modded.help.operator_instruction",
            "Run {command} from the console (or enable cheats in singleplayer); until then these commands will not run or tab-complete."
    );
    public static final TextKey MODDED_PROPERTIES_NONE = TextKey.of(
            "iris.modded.command.properties.none",
            "Properties: (none)"
    );
    public static final TextKey MODDED_PROPERTIES = TextKey.of(
            "iris.modded.command.properties.list",
            "Properties: {properties}"
    );

    private static final List<MessageKey> RUNTIME_KEYS = List.of(
            PREGEN_ALREADY_RUNNING,
            COMMAND_PERMISSION_DENIED,
            COMMAND_UNKNOWN,
            COMMAND_PLAYER_ONLY,
            COMMAND_IRIS_WORLD_REQUIRED,
            COMMAND_RELOAD_SUCCESS,
            COMMAND_RELOAD_FAILED,
            MODDED_HELP_UNKNOWN_SECTION,
            MODDED_HELP_BACK_HOVER,
            MODDED_HELP_COMMAND_PARAMETER,
            MODDED_HELP_BRIGADIER_TEXT,
            MODDED_HELP_OPERATOR_NOTICE,
            MODDED_HELP_OPERATOR_INSTRUCTION,
            MODDED_PROPERTIES_NONE,
            MODDED_PROPERTIES
    );
    private static final MessageCatalog CATALOG = createCatalog();

    private IrisMessages() {
    }

    public static MessageCatalog catalog() {
        return CATALOG;
    }

    public static MessageKey require(String id) {
        return CATALOG.require(id);
    }

    private static MessageCatalog createCatalog() {
        MessageCatalog.Builder builder = MessageCatalog.builder(VolmitLocales.ENGLISH);
        builder.addAll(DirectorMessages.keys());
        builder.addAll(BukkitLanguageMessages.keys());
        builder.addAll(BukkitDebugMessages.keys());
        builder.addAll(RUNTIME_KEYS);
        builder.addAll(BukkitCommandMessages.keys());
        builder.addAll(BukkitCommandMessagesExtended.keys());
        builder.addAll(DirectorCommandMessages.keys());
        builder.addAll(RuntimeUiMessages.keys());
        builder.addAll(BukkitRuntimeMessages.keys());
        builder.addAll(RuntimeProgressMessages.keys());
        builder.addAll(PackDownloadMessages.keys());
        builder.addAll(BukkitUiMessages.keys());
        builder.addAll(DesktopUiMessages.keys());
        for (IrisMessageContributor contributor : ServiceLoader.load(IrisMessageContributor.class, IrisMessages.class.getClassLoader())) {
            builder.addAll(contributor.keys());
        }
        return builder.build();
    }
}
