plugins {
    id 'java-library'
}

group = 'art.arcane'
version = rootProject.version

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    testImplementation('junit:junit:4.13.2')
}

tasks.named('jar', Jar).configure {
    archiveBaseName.set('iris-spi')
}
